/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import controladores.Temperatura;
import static controladores.setTimeout.setTimeout;
import java.awt.Color;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.SwingConstants;

/**
 *
 * @author braya
 */
public class FormTemperatura extends javax.swing.JPanel {

    /**
     * Creates new form FormTemperatura
     */
    public FormTemperatura() {
        initComponents();
         onlyNumber();
         comboadd();
    }
    private void onlyNumber(){
        NumeroConversor.addKeyListener(new KeyAdapter() {
         @Override
         public void keyTyped(KeyEvent e) {
         char c = e.getKeyChar();
          if (!((c >= '0') && (c <= '9') ||
         (c == KeyEvent.VK_BACK_SPACE) ||
         (c == KeyEvent.VK_DELETE))) {
          getToolkit().beep();
            e.consume();
          }
        }
      });
  }
        private void comboadd() {
            NumeroConversor.setFocusable(false);
            Minres.putClientProperty( "JComponent.roundRect", true );
            LogoLabel.setHorizontalAlignment(SwingConstants.CENTER);
            LogoLabel.setVerticalAlignment(SwingConstants.CENTER);
            cambio.setHorizontalAlignment(SwingConstants.CENTER);
            cambio.setVerticalAlignment(SwingConstants.CENTER);
            date.setHorizontalAlignment(SwingConstants.CENTER);
            date.setVerticalAlignment(SwingConstants.CENTER);
            SeleccionO.setRenderer(new CustomComboBoxR());
            SeleccionD.setRenderer(new CustomComboBoxR());         
    }
     private static class CustomComboBoxR extends DefaultListCellRenderer {
        @Override
        public java.awt.Component getListCellRendererComponent(javax.swing.JList<?> list,
                                                               Object value,
                                                               int index,
                                                               boolean isSelected,
                                                               boolean cellHasFocus) {
            java.awt.Component component = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
            // Personaliza el aspecto aquí (por ejemplo, cambia la fuente o el color de fondo)
            // Ejemplo: component.setFont(new Font("Arial", Font.BOLD, 14));
            // Ejemplo: component.setBackground(Color.YELLOW);            component.setBackground(Color.GRAY);
            if (isSelected) {
                this.setForeground(Color.BLUE);
                this.setBackground(Color.WHITE);
            } else {
                this.setBackground(Color.WHITE);
                this.setForeground(Color.GRAY);
            }
            return this;
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FormConversor = new javax.swing.JPanel();
        BotonConsulta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        SeleccionD = new javax.swing.JComboBox<>();
        SeleccionO = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        NumeroConversor = new javax.swing.JTextField();
        nameConsulta = new javax.swing.JLabel();
        LogoLabel = new javax.swing.JLabel();
        Minres = new javax.swing.JPanel();
        res = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        cambio = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 428));
        setVerifyInputWhenFocusTarget(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFocusable(false);
        jPanel1.setOpaque(false);

        FormConversor.setBackground(new java.awt.Color(255, 255, 255));
        FormConversor.setFocusable(false);

        BotonConsulta.setBackground(new java.awt.Color(0, 134, 190));
        BotonConsulta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonConsultaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonConsultaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BotonConsultaMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consultar");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout BotonConsultaLayout = new javax.swing.GroupLayout(BotonConsulta);
        BotonConsulta.setLayout(BotonConsultaLayout);
        BotonConsultaLayout.setHorizontalGroup(
            BotonConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonConsultaLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        BotonConsultaLayout.setVerticalGroup(
            BotonConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        SeleccionD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Destino de Temperatura", "Celcius", "Fahrenheit", "Kelvin" }));
        SeleccionD.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        SeleccionO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Origen de Temperatura", "Celcius", "Fahrenheit", "Kelvin" }));
        SeleccionO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        NumeroConversor.setForeground(new java.awt.Color(204, 204, 204));
        NumeroConversor.setText("Ingrese un valor a consultar");
        NumeroConversor.setBorder(null);
        NumeroConversor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NumeroConversorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NumeroConversorMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NumeroConversorMousePressed(evt);
            }
        });

        nameConsulta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nameConsulta.setText("Conversor de Temperatura");

        LogoLabel.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        LogoLabel.setForeground(new java.awt.Color(0, 153, 0));
        LogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/time.png"))); // NOI18N
        LogoLabel.setAlignmentX(0.5F);

        Minres.setBackground(new java.awt.Color(255, 255, 255));

        res.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N

        javax.swing.GroupLayout MinresLayout = new javax.swing.GroupLayout(Minres);
        Minres.setLayout(MinresLayout);
        MinresLayout.setHorizontalGroup(
            MinresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MinresLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(res)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        MinresLayout.setVerticalGroup(
            MinresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MinresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(res, javax.swing.GroupLayout.DEFAULT_SIZE, 19, Short.MAX_VALUE)
                .addContainerGap())
        );

        date.setBackground(new java.awt.Color(255, 255, 255));
        date.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        date.setForeground(new java.awt.Color(0, 134, 190));
        date.setToolTipText("");

        cambio.setBackground(new java.awt.Color(255, 255, 255));
        cambio.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        cambio.setForeground(new java.awt.Color(0, 134, 190));
        cambio.setToolTipText("");

        javax.swing.GroupLayout FormConversorLayout = new javax.swing.GroupLayout(FormConversor);
        FormConversor.setLayout(FormConversorLayout);
        FormConversorLayout.setHorizontalGroup(
            FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormConversorLayout.createSequentialGroup()
                .addGroup(FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormConversorLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(SeleccionO, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(SeleccionD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormConversorLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NumeroConversor, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormConversorLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(BotonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormConversorLayout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(Minres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FormConversorLayout.createSequentialGroup()
                            .addGap(136, 136, 136)
                            .addGroup(FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(15, 15, 15))
                        .addGroup(FormConversorLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(FormConversorLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(nameConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        FormConversorLayout.setVerticalGroup(
            FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormConversorLayout.createSequentialGroup()
                .addComponent(LogoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cambio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(nameConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(NumeroConversor, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(FormConversorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeleccionO, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(BotonConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Minres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormConversor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FormConversor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 472, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConsultaMouseEntered
        BotonConsulta.setBackground(new Color(0,156,223));
    }//GEN-LAST:event_BotonConsultaMouseEntered

    private void BotonConsultaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConsultaMouseExited
        BotonConsulta.setBackground(new Color(0,134,190));
    }//GEN-LAST:event_BotonConsultaMouseExited

    private void BotonConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonConsultaMousePressed
        LogoLabel.setIcon(new ImageIcon(getClass().getResource("/images/loader.gif")));
        if(!"Ingrese un valor a consultar".equals(NumeroConversor.getText())){
            double valor = Double.parseDouble(NumeroConversor.getText().trim());
            String origen = SeleccionO.getEditor().getItem().toString();
            String destino = SeleccionD.getEditor().getItem().toString();
             Temperatura t = new Temperatura(valor, origen, destino);
             double result = t.temp();
             System.out.println("result " +result);
             setTimeout(() -> {
             DecimalFormat decimalFormat = new DecimalFormat("#.##");
             System.out.println(result);
                LogoLabel.setIcon(new ImageIcon(getClass().getResource("/images/climate.png")));
                cambio.setText("De "+origen+" A "+destino);
                date.setText(decimalFormat.format(result));
                }, 1000);
            }else{
            res.setText("Ingrese un valor de 1 a 10");
            res.setForeground(Color.WHITE);
            Minres.setBackground(Color.RED);
            LogoLabel.setIcon(new ImageIcon(getClass().getResource("/images/change3.png")));
        }
    }//GEN-LAST:event_BotonConsultaMousePressed

    private void NumeroConversorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumeroConversorMouseEntered
        NumeroConversor.setFocusable(true);
        NumeroConversor.setText("");
        res.setText("");
        Minres.setBackground(Color.WHITE);
        NumeroConversor.setForeground(Color.black);
    }//GEN-LAST:event_NumeroConversorMouseEntered

    private void NumeroConversorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumeroConversorMouseExited
        if(NumeroConversor.getText().trim().isEmpty()){
            NumeroConversor.setText("Ingrese un valor a consultar");
            NumeroConversor.setForeground(new Color(204,204,204));
        }
    }//GEN-LAST:event_NumeroConversorMouseExited

    private void NumeroConversorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NumeroConversorMousePressed
        NumeroConversor.setText("");
        NumeroConversor.setForeground(Color.black);   
    }//GEN-LAST:event_NumeroConversorMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonConsulta;
    private javax.swing.JPanel FormConversor;
    private javax.swing.JLabel LogoLabel;
    private javax.swing.JPanel Minres;
    private javax.swing.JTextField NumeroConversor;
    private javax.swing.JComboBox<String> SeleccionD;
    private javax.swing.JComboBox<String> SeleccionO;
    private javax.swing.JLabel cambio;
    private javax.swing.JLabel date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameConsulta;
    private javax.swing.JLabel res;
    // End of variables declaration//GEN-END:variables
}
