/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Insets;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.UIManager;
/**
 *
 * 
 * @author braya
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    int xMouse, yMosue;
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargaConversor(new Fconversor());
        ComboListen();
        //EscalarImagen(loader , "src/images/loader.");
    }
    private void ComboListen(){
            metodo.putClientProperty( "JComponent.roundRect", true );
            UIManager.put( "ScrollBar.thumbArc", 3 );
            UIManager.put( "ScrollBar.thumbInsets", new Insets( 2, 2, 2, 2 ) );
            metodo.addItemListener((ItemEvent event) -> {
            String item = (String) event.getItem();
            //System.out.println("Affected items: " + item + "\n");
            if (event.getStateChange() == ItemEvent.SELECTED) {
                if("Conversor Moneda".equals(item)){
                    System.out.println(item+" Correcto");
                    cargaConversor(new Fconversor());
                }
                if("Conversor Temperatura".equals(item)){
                    cargaTemperatura(new FormTemperatura());
                }
            }
            if (event.getStateChange() == ItemEvent.DESELECTED){
               // System.out.println(item + " deselected\n");
            }
          });
    }
    private void cargaConversor(Fconversor p) {
        p.setLocation(0,0); 
        Dimension tamano = Form.getPreferredSize();
        p.setSize(tamano);
        Form.removeAll();
        Form.add(p,BorderLayout.CENTER);
        Form.setVisible(true);
        Form.revalidate();
        Form.repaint(); 
    }
    private void cargaTemperatura(FormTemperatura p) {
        p.setLocation(0,0); 
        Dimension tamano = Form.getPreferredSize();
        p.setSize(tamano);
        Form.removeAll();
        Form.add(p,BorderLayout.CENTER);
        Form.setVisible(true);
        Form.revalidate();
        Form.repaint(); 
    }
    private void EscalarImagen(JLabel labelNmae , String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new  ImageIcon(image.getImage().getScaledInstance(labelNmae.getWidth(),labelNmae.getHeight(),Image.SCALE_DEFAULT));
        labelNmae.setIcon(icon);
        this.repaint();
    }
   @Override
   public Image getIconImage(){
       return Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/change3.png"));
   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Base = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        Nameapp = new javax.swing.JLabel();
        SeleccionMetodo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        link = new javax.swing.JLabel();
        metodo = new javax.swing.JComboBox<>();
        namelink = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fondoLogo = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        header = new javax.swing.JPanel();
        Form = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        Base.setBackground(new java.awt.Color(219, 225, 227));
        Base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/convert2.png"))); // NOI18N
        logo.setText("logo");
        Base.add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 140, 130));

        Nameapp.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        Nameapp.setForeground(new java.awt.Color(255, 255, 255));
        Nameapp.setText("Convertidor");
        Nameapp.setToolTipText("");
        Base.add(Nameapp, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, 190, 50));

        SeleccionMetodo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SeleccionMetodo.setForeground(new java.awt.Color(255, 255, 255));
        SeleccionMetodo.setText("Seleccione un Metodo");
        Base.add(SeleccionMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, 200, 30));
        Base.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 450, 230, 10));

        link.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/neu.png"))); // NOI18N
        link.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkMouseClicked(evt);
            }
        });
        Base.add(link, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 50, 60));

        metodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Conversor Moneda", "Conversor Temperatura" }));
        Base.add(metodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 160, 40));

        namelink.setForeground(new java.awt.Color(255, 255, 255));
        namelink.setText("www.youvidplay.com");
        Base.add(namelink, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 430, 120, 20));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Creado por Brayan R.C");
        Base.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 460, 140, 30));

        fondoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/city.png"))); // NOI18N
        Base.add(fondoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 290, 490));

        cerrar.setBackground(new java.awt.Color(255, 51, 51));
        cerrar.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        cerrar.setText(" X");
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cerrarMouseExited(evt);
            }
        });
        Base.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        header.setBackground(new java.awt.Color(255, 255, 255));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        Base.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 30));

        Form.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout FormLayout = new javax.swing.GroupLayout(Form);
        Form.setLayout(FormLayout);
        FormLayout.setHorizontalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        FormLayout.setVerticalGroup(
            FormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        Base.add(Form, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 540, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Base, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
        // TODO add your handling code here:
          xMouse = evt.getX();
          yMosue = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMosue);
    }//GEN-LAST:event_headerMouseDragged

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        System.exit(0);
        
    }//GEN-LAST:event_cerrarMouseClicked

    private void cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseEntered
        cerrar.setOpaque(true);
        cerrar.setBackground(Color.red);
        cerrar.setForeground(Color.white);
    }//GEN-LAST:event_cerrarMouseEntered

    private void cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseExited
        cerrar.setBackground(Color.white);
        cerrar.setForeground(Color.black);
    }//GEN-LAST:event_cerrarMouseExited

    private void linkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkMouseClicked
        try{
            Desktop.getDesktop().browse(new URL("https://youvidplay.com").toURI());
        }
        catch(IOException | URISyntaxException e)
                {}
    }//GEN-LAST:event_linkMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Base;
    private javax.swing.JPanel Form;
    private javax.swing.JLabel Nameapp;
    private javax.swing.JLabel SeleccionMetodo;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel fondoLogo;
    private javax.swing.JPanel header;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel link;
    private javax.swing.JLabel logo;
    private javax.swing.JComboBox<String> metodo;
    private javax.swing.JLabel namelink;
    // End of variables declaration//GEN-END:variables


}
